In [1]:
import pandas as pd

In [2]:
import numpy as np

In [4]:
a = np.loadtxt
a = np.genfromtxt

In [27]:
b = pd.read_csv('acci.csv', encoding='cp949') # load

In [86]:
b.info() # dataFrame확인하기 
# padas에서는 object가 문자라고 생각하면됨!

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10365 entries, 0 to 10364
Data columns (total 16 columns):
사고지역관리번호       10365 non-null int64
사고년도           10365 non-null int64
사고유형구분         10365 non-null object
위치코드           10365 non-null int64
시도시군구명         10365 non-null object
사고지역위치명        10365 non-null object
발생건수           10365 non-null int64
사상자수           10365 non-null int64
사망자수           10365 non-null int64
중상자수           10365 non-null int64
경상자수           10365 non-null int64
부상자수           10365 non-null int64
위도             10365 non-null float64
경도             10365 non-null float64
사고다발지역폴리곤정보    10365 non-null object
데이터기준일자        10365 non-null object
dtypes: float64(2), int64(9), object(5)
memory usage: 1.3+ MB

In [88]:
b.describe() # summary

,사고지역관리번호,사고년도,위치코드,발생건수,사상자수,사망자수,중상자수,경상자수,부상자수,위도,경도
count,1.036500e+04,10365.000000,1.036500e+04,10365.000000,10365.000000,10365.000000,10365.000000,10365.000000,10365.000000,10365.000000,10365.000000
mean,2.015809e+06,2014.731693,6.909470e+07,4.750796,5.018138,0.234250,2.389194,2.046792,0.348288,36.596723,127.540724
std,1.932015e+03,1.955133,1.018650e+08,2.038119,2.275687,0.508633,1.743488,1.569080,0.706061,1.057973,0.856784
min,2.013060e+06,2012.000000,1.111000e+07,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,33.247238,126.257418
25%,2.014109e+06,2013.000000,2.623000e+07,3.000000,4.000000,0.000000,1.000000,1.000000,0.000000,35.830915,126.913266
50%,2.016146e+06,2015.000000,4.113500e+07,4.000000,4.000000,0.000000,2.000000,2.000000,0.000000,37.150031,127.086867
75%,2.017050e+06,2016.000000,4.713000e+07,5.000000,6.000000,0.000000,3.000000,3.000000,1.000000,37.522943,128.531153
max,2.019066e+06,2018.000000,5.021040e+08,27.000000,31.000000,4.000000,22.000000,15.000000,9.000000,38.210994,129.503616

In [97]:
b.describe(include='object') # summary - 문자열만 보기(object)

,사고유형구분,시도시군구명,사고지역위치명,사고다발지역폴리곤정보,데이터기준일자
count,10365,10365,10365,10365,10365
unique,5,2014,8568,10322,1
top,보행노인,대구광역시 달서구1,대구광역시 서구 비산동(북비산네거리 부근),"{type:Polygon,coordinates:[[[127.0166753,37.29...",2019-10-10
freq,3919,25,10,2,10365

In [98]:
b.describe(include='all') # summary - 전체보기

,사고지역관리번호,사고년도,사고유형구분,위치코드,시도시군구명,사고지역위치명,발생건수,사상자수,사망자수,중상자수,경상자수,부상자수,위도,경도,사고다발지역폴리곤정보,데이터기준일자
count,1.036500e+04,10365.000000,10365,1.036500e+04,10365,10365,10365.000000,10365.000000,10365.000000,10365.000000,10365.000000,10365.000000,10365.000000,10365.000000,10365,10365
unique,NaN,NaN,5,NaN,2014,8568,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10322,1
top,NaN,NaN,보행노인,NaN,대구광역시 달서구1,대구광역시 서구 비산동(북비산네거리 부근),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{type:Polygon,coordinates:[[[127.0166753,37.29...",2019-10-10
freq,NaN,NaN,3919,NaN,25,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,10365
mean,2.015809e+06,2014.731693,NaN,6.909470e+07,NaN,NaN,4.750796,5.018138,0.234250,2.389194,2.046792,0.348288,36.596723,127.540724,NaN,NaN
std,1.932015e+03,1.955133,NaN,1.018650e+08,NaN,NaN,2.038119,2.275687,0.508633,1.743488,1.569080,0.706061,1.057973,0.856784,NaN,NaN
min,2.013060e+06,2012.000000,NaN,1.111000e+07,NaN,NaN,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,33.247238,126.257418,NaN,NaN
25%,2.014109e+06,2013.000000,NaN,2.623000e+07,NaN,NaN,3.000000,4.000000,0.000000,1.000000,1.000000,0.000000,35.830915,126.913266,NaN,NaN
50%,2.016146e+06,2015.000000,NaN,4.113500e+07,NaN,NaN,4.000000,4.000000,0.000000,2.000000,2.000000,0.000000,37.150031,127.086867,NaN,NaN
75%,2.017050e+06,2016.000000,NaN,4.713000e+07,NaN,NaN,5.000000,6.000000,0.000000,3.000000,3.000000,1.000000,37.522943,128.531153,NaN,NaN
max,2.019066e+06,2018.000000,NaN,5.021040e+08,NaN,NaN,27.000000,31.000000,4.000000,22.000000,15.000000,9.000000,38.210994,129.503616,NaN,NaN

In [91]:
b.describe().T #  열과 행 바꾸기 .T

,count,mean,std,min,25%,50%,75%,max
사고지역관리번호,10365.0,2.015809e+06,1.932015e+03,2.013060e+06,2.014109e+06,2.016146e+06,2.017050e+06,2.019066e+06
사고년도,10365.0,2.014732e+03,1.955133e+00,2.012000e+03,2.013000e+03,2.015000e+03,2.016000e+03,2.018000e+03
위치코드,10365.0,6.909470e+07,1.018650e+08,1.111000e+07,2.623000e+07,4.113500e+07,4.713000e+07,5.021040e+08
발생건수,10365.0,4.750796e+00,2.038119e+00,1.000000e+00,3.000000e+00,4.000000e+00,5.000000e+00,2.700000e+01
사상자수,10365.0,5.018138e+00,2.275687e+00,0.000000e+00,4.000000e+00,4.000000e+00,6.000000e+00,3.100000e+01
사망자수,10365.0,2.342499e-01,5.086327e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.000000e+00
중상자수,10365.0,2.389194e+00,1.743488e+00,0.000000e+00,1.000000e+00,2.000000e+00,3.000000e+00,2.200000e+01
경상자수,10365.0,2.046792e+00,1.569080e+00,0.000000e+00,1.000000e+00,2.000000e+00,3.000000e+00,1.500000e+01
부상자수,10365.0,3.482875e-01,7.060609e-01,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,9.000000e+00
위도,10365.0,3.659672e+01,1.057973e+00,3.324724e+01,3.583092e+01,3.715003e+01,3.752294e+01,3.821099e+01
경도,10365.0,1.275407e+02,8.567837e-01,1.262574e+02,1.269133e+02,1.270869e+02,1.285312e+02,1.295036e+02

In [82]:
dir(b)

['T',
 '_AXIS_ALIASES',
 '_AXIS_IALIASES',
 '_AXIS_LEN',
 '_AXIS_NAMES',
 '_AXIS_NUMBERS',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_add_numeric_operations',
 '_add_series_only_operations',
 '_add_series_or_dataframe_operations',
 '_agg_by_level',
 '_agg_examples_doc',
 '_agg_summary_and_see_also_doc',
 '_aggregate',
 '_aggregate_multiple_funcs',
 '_align_frame',
 '_align_series',
 '_box_col_values',
 '_box_item_values',
 '_builtin_table',
 '_check_inplace_setting',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_percentile',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_combine_const',
 '_combine_frame',
 '_combine_match_columns',
 '_combine_match_index',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_axes_dict_from',
 '_construct_axes_from_arguments',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_sliced',
 '_convert',
 '_count_level',
 '_create_indexer',
 '_cython_table',
 '_data',
 '_deprecations',
 '_dir_additions',
 '_dir_deletions',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_from_arrays',
 '_from_axes',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cacher',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_space_character_free_column_resolvers',
 '_get_value',
 '_get_values',
 '_getitem_bool_array',
 '_getitem_frame',
 '_getitem_multilevel',
 '_gotitem',
 '_iget_item_cache',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_internal_get_values',
 '_internal_names',
 '_internal_names_set',
 '_is_builtin_func',
 '_is_cached',
 '_is_copy',
 '_is_cython_func',
 '_is_datelike_mixed_type',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_numeric_mixed_type',
 '_is_view',
 '_ix',
 '_ixs',
 '_join_compat',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_needs_reindex_multi',
 '_obj_with_exclusions',
 '_protect_consolidate',
 '_reduce',
 '_reindex_axes',
 '_reindex_columns',
 '_reindex_index',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_selected_obj',
 '_selection',
 '_selection_list',
 '_selection_name',
 '_series',
 '_set_as_cached',
 '_set_axis',
 '_set_axis_name',
 '_set_is_copy',
 '_set_item',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_setup_axes',
 '_shallow_copy',
 '_slice',
 '_stat_axis',
 '_stat_axis_name',
 '_stat_axis_number',
 '_to_dict_of_blocks',
 '_try_aggregate_string_function',
 '_typ',
 '_unpickle_frame_compat',
 '_unpickle_matrix_compat',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 '_xs',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'append',
 'apply',
 'applymap',
 'as_matrix',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'axes',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'clip',
 'clip_lower',
 'clip_upper',
 'columns',
 'combine',
 'combine_first',
 'compound',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'floordiv',
 'from_dict',
 'from_records',
 'ftypes',
 'ge',
 'get',
 'get_dtype_counts',
 'get_ftype_counts',
 'get_values',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isin',
 'isna',
 'isnull',
 'items',
 'iteritems',
 'iterrows',
 'itertuples',
 'ix',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lookup',
 'lt',
 'mad',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'slice_shift',
 'sort_index',
 'sort_values',
 'sparse',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dense',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_msgpack',
 'to_numpy',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sparse',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tshift',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'values',
 'var',
 'where',
 'xs',
 '경도',
 '경상자수',
 '데이터기준일자',
 '발생건수',
 '부상자수',
 '사고년도',
 '사고다발지역폴리곤정보',
 '사고유형구분',
 '사고지역관리번호',
 '사고지역위치명',
 '사망자수',
 '사상자수',
 '시도시군구명',
 '위도',
 '위치코드',
 '중상자수']

In [28]:
type(b)

pandas.core.frame.DataFrame

In [29]:
b

,사고지역관리번호,사고년도,사고유형구분,위치코드,시도시군구명,사고지역위치명,발생건수,사상자수,사망자수,중상자수,경상자수,부상자수,위도,경도,사고다발지역폴리곤정보,데이터기준일자
0,2013060,2012,스쿨존어린이,11110001,서울특별시 종로구1,서울특별시 종로구 혜화동(혜화초교 부근),2,2,0,1,1,0,37.588413,126.999607,"{type:Polygon,coordinates:[[[127.002009,37.590...",2019-10-10
1,2013060,2012,스쿨존어린이,11290001,서울특별시 성북구1,서울특별시 성북구 종암동(숭례초교 부근),2,2,0,0,1,1,37.595505,127.035733,"{type:Polygon,coordinates:[[[127.0381354,37.59...",2019-10-10
2,2013060,2012,스쿨존어린이,11290002,서울특별시 성북구2,서울특별시 성북구 동소문동7가(정덕초교 부근),2,2,0,2,0,0,37.597571,127.014564,"{type:Polygon,coordinates:[[[127.0169658,37.59...",2019-10-10
3,2013060,2012,스쿨존어린이,11290003,서울특별시 성북구3,서울특별시 성북구 석관동(석관초교 부근),3,3,0,2,1,0,37.610429,127.059596,"{type:Polygon,coordinates:[[[127.0619982,37.61...",2019-10-10
4,2013060,2012,스쿨존어린이,11320001,서울특별시 도봉구1,서울특별시 도봉구 쌍문동(쌍문초교 부근),2,2,0,0,2,0,37.648129,127.024430,"{type:Polygon,coordinates:[[[127.0268336,37.65...",2019-10-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10360,2019066,2018,무단횡단,280641002,경기 파주2,경기도 파주시 금촌동(우리은행 파주금융센터 부근),5,7,0,2,5,0,37.757022,126.773592,"{type:Polygon,coordinates:[[[126.77628656,37.7...",2019-10-10
10361,2019066,2018,무단횡단,280641003,경기 파주3,경기도 파주시 조리읍(봉일천우체국 부근),5,5,0,2,3,0,37.743755,126.806671,"{type:Polygon,coordinates:[[[126.80936607,37.7...",2019-10-10
10362,2019066,2018,무단횡단,280641004,경기 파주4,경기도 파주시 금촌동(금촌사거리 부근),4,4,0,2,2,0,37.763186,126.773463,"{type:Polygon,coordinates:[[[126.77615816,37.7...",2019-10-10
10363,2019066,2018,무단횡단,280941001,경기 구리1,경기도 구리시 수택동(세븐일레븐 구리으뜸점 부근),6,6,0,2,4,0,37.598290,127.136542,"{type:Polygon,coordinates:[[[127.13923669,37.5...",2019-10-10
10364,2019066,2018,무단횡단,281041001,경기 포천1,경기도 포천시 소흘읍(송우순복음교회 부근),4,5,0,1,4,0,37.825582,127.143884,"{type:Polygon,coordinates:[[[127.14657884,37.8...",2019-10-10

In [19]:
b.values # numpy format

array([[2013060, 2012, '스쿨존어린이', ..., 126.9996071,
        '{type:Polygon,coordinates:[[[127.002009,37.5903242],[127.0016037,37.5905996],[127.0011492,37.5908213],[127.0006568,37.5909836],[127.0001385,37.5910826],[126.9996071,37.5911159],[126.9990757,37.5910826],[126.9985574,37.5909836],[126.998065,37.5908213],[126.9976105,37.5905996],[126.9972052,37.5903242],[126.9968591,37.5900017],[126.9965806,37.58964],[126.9963766,37.5892481],[126.9962522,37.5888357],[126.9962104,37.5884129],[126.9962522,37.58799],[126.9963767,37.5875776],[126.9965807,37.5871857],[126.9968592,37.5868241],[126.9972053,37.5865016],[126.9976106,37.5862261],[126.9980651,37.5860045],[126.9985575,37.5858422],[126.9990758,37.5857432],[126.9996071,37.5857099],[127.0001384,37.5857432],[127.0006567,37.5858422],[127.0011491,37.5860045],[127.0016036,37.5862261],[127.0020089,37.5865016],[127.002355,37.5868241],[127.0026335,37.5871857],[127.0028375,37.5875776],[127.002962,37.58799],[127.0030038,37.5884129],[127.002962,37.5888357],[127.0028376,37.5892481],[127.0026336,37.58964],[127.0023551,37.5900017],[127.002009,37.5903242]]]}',
        '2019-10-10'],
       [2013060, 2012, '스쿨존어린이', ..., 127.03573324,
        '{type:Polygon,coordinates:[[[127.0381354,37.597416],[127.03773,37.5976915],[127.0372755,37.5979131],[127.036783,37.5980754],[127.0362647,37.5981744],[127.0357332,37.5982077],[127.0352018,37.5981744],[127.0346835,37.5980754],[127.034191,37.5979131],[127.0337365,37.5976915],[127.0333311,37.597416],[127.0329849,37.5970935],[127.0327064,37.5967318],[127.0325024,37.5963399],[127.032378,37.5959275],[127.0323362,37.5955047],[127.0323781,37.5950818],[127.0325025,37.5946694],[127.0327065,37.5942776],[127.0329851,37.5939159],[127.0333312,37.5935934],[127.0337366,37.5933179],[127.0341911,37.5930963],[127.0346835,37.592934],[127.0352018,37.592835],[127.0357332,37.5928017],[127.0362646,37.592835],[127.0367829,37.592934],[127.0372754,37.5930963],[127.0377299,37.5933179],[127.0381352,37.5935934],[127.0384814,37.5939159],[127.03876,37.5942776],[127.038964,37.5946694],[127.0390884,37.5950818],[127.0391303,37.5955047],[127.0390885,37.5959275],[127.038964,37.5963399],[127.0387601,37.5967318],[127.0384815,37.5970935],[127.0381354,37.597416]]]}',
        '2019-10-10'],
       [2013060, 2012, '스쿨존어린이', ..., 127.01456358,
        '{type:Polygon,coordinates:[[[127.0169658,37.5994827],[127.0165604,37.5997582],[127.0161059,37.5999798],[127.0156134,37.6001421],[127.015095,37.6002411],[127.0145636,37.6002744],[127.0140321,37.6002411],[127.0135138,37.6001421],[127.0130213,37.5999798],[127.0125667,37.5997582],[127.0121614,37.5994827],[127.0118152,37.5991602],[127.0115367,37.5987985],[127.0113327,37.5984067],[127.0112083,37.5979942],[127.0111665,37.5975714],[127.0112083,37.5971485],[127.0113328,37.5967361],[127.0115368,37.5963443],[127.0118153,37.5959826],[127.0121615,37.5956601],[127.0125669,37.5953847],[127.0130214,37.5951631],[127.0135138,37.5950007],[127.0140322,37.5949017],[127.0145636,37.5948685],[127.015095,37.5949017],[127.0156133,37.5950007],[127.0161058,37.5951631],[127.0165603,37.5953847],[127.0169656,37.5956601],[127.0173118,37.5959826],[127.0175904,37.5963443],[127.0177944,37.5967361],[127.0179188,37.5971485],[127.0179607,37.5975714],[127.0179189,37.5979942],[127.0177945,37.5984067],[127.0175905,37.5987985],[127.017312,37.5991602],[127.0169658,37.5994827]]]}',
        '2019-10-10'],
       ...,
       [2019066, 2018, '무단횡단', ..., 126.77346321,
        '{type:Polygon,coordinates:[[[126.77615816,37.76318599],[126.77610638,37.76277035],[126.77595302,37.76237068],[126.77570398,37.76200235],[126.77536883,37.76167949],[126.77496045,37.76141453],[126.77449453,37.76121765],[126.77398897,37.76109641],[126.77346321,37.76105547],[126.77293746,37.76109641],[126.7724319,37.76121765],[126.77196598,37.76141453],[126.7715576,37.76167949],[126.77122245,37.76200235],[126.77097341,37.76237068],[126.77082005,37.76277035],[126.77076827,37.76318599],[126.77082005,37.76360163],[126.77097341,37.76400129],[126.77122245,37.76436961],[126.7715576,37.76469246],[126.77196598,37.7649574],[126.7724319,37.76515428],[126.77293746,37.76527551],[126.77346321,37.76531644],[126.77398897,37.76527551],[126.77449453,37.76515428],[126.77496045,37.7649574],[126.77536883,37.76469246],[126.77570398,37.76436961],[126.77595302,37.76400129],[126.77610638,37.76360163],[126.77615816,37.76318599]]]}',
        '2019-10-10'],
       [2019066, 2018, '무단횡단', ..., 127.13654175,
        '{type:Polygon,coordinates:[[[127.13923669,37.59828952],[127.13918491,37.59787295],[127.13903155,37.5974724],[127.13878251,37.59710324],[127.13844736,37.59677967],[127.13803898,37.59651412],[127.13757306,37.5963168],[127.13706751,37.59619529],[127.13654175,37.59615426],[127.13601599,37.59619529],[127.13551044,37.5963168],[127.13504452,37.59651412],[127.13463613,37.59677967],[127.13430098,37.59710324],[127.13405194,37.5974724],[127.13389859,37.59787295],[127.1338468,37.59828952],[127.13389859,37.59870608],[127.13405194,37.59910663],[127.13430098,37.59947578],[127.13463613,37.59979934],[127.13504452,37.60006487],[127.13551044,37.60026218],[127.13601599,37.60038369],[127.13654175,37.60042471],[127.13706751,37.60038369],[127.13757306,37.60026218],[127.13803898,37.60006487],[127.13844736,37.59979934],[127.13878251,37.59947578],[127.13903155,37.59910663],[127.13918491,37.59870608],[127.13923669,37.59828952]]]}',
        '2019-10-10'],
       [2019066, 2018, '무단횡단', ..., 127.14388389,
        '{type:Polygon,coordinates:[[[127.14657884,37.82558221],[127.14652706,37.82516692],[127.1463737,37.82476759],[127.14612466,37.82439956],[127.14578951,37.82407698],[127.14538112,37.82381225],[127.1449152,37.82361553],[127.14440965,37.82349439],[127.14388389,37.82345349],[127.14335813,37.82349439],[127.14285258,37.82361553],[127.14238666,37.82381225],[127.14197828,37.82407698],[127.14164313,37.82439956],[127.14139409,37.82476759],[127.14124073,37.82516692],[127.14118895,37.82558221],[127.14124073,37.82599749],[127.14139409,37.82639681],[127.14164313,37.82676483],[127.14197828,37.8270874],[127.14238666,37.82735212],[127.14285258,37.82754883],[127.14335813,37.82766996],[127.14388389,37.82771086],[127.14440965,37.82766996],[127.1449152,37.82754883],[127.14538112,37.82735212],[127.14578951,37.8270874],[127.14612466,37.82676483],[127.1463737,37.82639681],[127.14652706,37.82599749],[127.14657884,37.82558221]]]}',
        '2019-10-10']], dtype=object)

In [20]:
b['사고년도']

0        2012
1        2012
2        2012
3        2012
4        2012
         ...
10360    2018
10361    2018
10362    2018
10363    2018
10364    2018
Name: 사고년도, Length: 10365, dtype: int64

In [21]:
type(b['사고년도'])

pandas.core.series.Series

In [31]:
b.위치코드 #

0         11110001
1         11290001
2         11290002
3         11290003
4         11320001
           ...
10360    280641002
10361    280641003
10362    280641004
10363    280941001
10364    281041001
Name: 위치코드, Length: 10365, dtype: int64

In [32]:
b.iloc[0]

사고지역관리번호                                                 2013060
사고년도                                                        2012
사고유형구분                                                    스쿨존어린이
위치코드                                                    11110001
시도시군구명                                                서울특별시 종로구1
사고지역위치명                                   서울특별시 종로구 혜화동(혜화초교 부근)
발생건수                                                           2
사상자수                                                           2
사망자수                                                           0
중상자수                                                           1
경상자수                                                           1
부상자수                                                           0
위도                                                       37.5884
경도                                                           127
사고다발지역폴리곤정보    {type:Polygon,coordinates:[[[127.002009,37.590...
데이터기준일자                                               2019-10-10
Name: 0, dtype: object

In [33]:
.iloc[1:100]

,사고지역관리번호,사고년도,사고유형구분,위치코드,시도시군구명,사고지역위치명,발생건수,사상자수,사망자수,중상자수,경상자수,부상자수,위도,경도,사고다발지역폴리곤정보,데이터기준일자
1,2013060,2012,스쿨존어린이,11290001,서울특별시 성북구1,서울특별시 성북구 종암동(숭례초교 부근),2,2,0,0,1,1,37.595505,127.035733,"{type:Polygon,coordinates:[[[127.0381354,37.59...",2019-10-10
2,2013060,2012,스쿨존어린이,11290002,서울특별시 성북구2,서울특별시 성북구 동소문동7가(정덕초교 부근),2,2,0,2,0,0,37.597571,127.014564,"{type:Polygon,coordinates:[[[127.0169658,37.59...",2019-10-10
3,2013060,2012,스쿨존어린이,11290003,서울특별시 성북구3,서울특별시 성북구 석관동(석관초교 부근),3,3,0,2,1,0,37.610429,127.059596,"{type:Polygon,coordinates:[[[127.0619982,37.61...",2019-10-10
4,2013060,2012,스쿨존어린이,11320001,서울특별시 도봉구1,서울특별시 도봉구 쌍문동(쌍문초교 부근),2,2,0,0,2,0,37.648129,127.024430,"{type:Polygon,coordinates:[[[127.0268336,37.65...",2019-10-10
5,2013060,2012,스쿨존어린이,11350001,서울특별시 노원구1,서울특별시 노원구 상계동(동일초교 부근),2,2,1,1,0,0,37.664437,127.056828,"{type:Polygon,coordinates:[[[127.0592324,37.66...",2019-10-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2013097,2012,보행어린이,27290008,대구광역시 달서구8,대구광역시 달서구 상인동(꼬꼬마놀이방 부근),4,4,0,3,1,0,35.810940,128.536826,"{type:Polygon,coordinates:[[[128.538391,35.812...",2019-10-10
96,2013097,2012,보행어린이,27710001,대구광역시 달성군1,대구광역시 달성군 논공읍(대신빌딩 부근),4,4,0,1,3,0,35.729304,128.445212,"{type:Polygon,coordinates:[[[128.4467751,35.73...",2019-10-10
97,2013097,2012,보행어린이,28170001,인천광역시 남구1,인천광역시 남구 주안동(태광빌라 부근),3,3,0,1,1,1,37.453179,126.695052,"{type:Polygon,coordinates:[[[126.6966503,37.45...",2019-10-10
98,2013097,2012,보행어린이,28185001,인천광역시 연수구1,인천광역시 연수구 송도동(극동엔지니어링(주) 부근),4,4,0,3,1,0,37.395115,126.650604,"{type:Polygon,coordinates:[[[126.6522011,37.39...",2019-10-10
99,2013097,2012,보행어린이,28200001,인천광역시 남동구1,인천광역시 남동구 만수동(햇빛소비자유통 부근),4,4,1,1,2,0,37.463479,126.724085,"{type:Polygon,coordinates:[[[126.7256833,37.46...",2019-10-10

In [38]:
b.iloc[1:100, 1]

1     2012
2     2012
3     2012
4     2012
5     2012
      ...
95    2012
96    2012
97    2012
98    2012
99    2012
Name: 사고년도, Length: 99, dtype: int64

In [39]:
b.loc(0)

In [40]:
b.log[o:3]

AttributeError: 'DataFrame' object has no attribute 'log'

In [37]:
b.log[0:3]

AttributeError: 'DataFrame' object has no attribute 'log'

In [42]:
b.loc[0:,3, '위치코드':'시도시군구면']

TypeError: cannot do label indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [3] of <class 'int'>

In [45]:
b.iat(0,2)

TypeError: __call__() takes from 1 to 2 positional arguments but 3 were given

In [47]:
b[b['사고년도']== 2012]

,사고지역관리번호,사고년도,사고유형구분,위치코드,시도시군구명,사고지역위치명,발생건수,사상자수,사망자수,중상자수,경상자수,부상자수,위도,경도,사고다발지역폴리곤정보,데이터기준일자
0,2013060,2012,스쿨존어린이,11110001,서울특별시 종로구1,서울특별시 종로구 혜화동(혜화초교 부근),2,2,0,1,1,0,37.588413,126.999607,"{type:Polygon,coordinates:[[[127.002009,37.590...",2019-10-10
1,2013060,2012,스쿨존어린이,11290001,서울특별시 성북구1,서울특별시 성북구 종암동(숭례초교 부근),2,2,0,0,1,1,37.595505,127.035733,"{type:Polygon,coordinates:[[[127.0381354,37.59...",2019-10-10
2,2013060,2012,스쿨존어린이,11290002,서울특별시 성북구2,서울특별시 성북구 동소문동7가(정덕초교 부근),2,2,0,2,0,0,37.597571,127.014564,"{type:Polygon,coordinates:[[[127.0169658,37.59...",2019-10-10
3,2013060,2012,스쿨존어린이,11290003,서울특별시 성북구3,서울특별시 성북구 석관동(석관초교 부근),3,3,0,2,1,0,37.610429,127.059596,"{type:Polygon,coordinates:[[[127.0619982,37.61...",2019-10-10
4,2013060,2012,스쿨존어린이,11320001,서울특별시 도봉구1,서울특별시 도봉구 쌍문동(쌍문초교 부근),2,2,0,0,2,0,37.648129,127.024430,"{type:Polygon,coordinates:[[[127.0268336,37.65...",2019-10-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1753,2013114,2012,무단횡단,502103002,제주 서귀포2,제주특별자치도 서귀포시 서귀동((한남투자) 부근),4,4,0,4,0,0,33.252512,126.561100,"{type:Polygon,coordinates:[[[126.5633766,33.25...",2019-10-10
1754,2013114,2012,무단횡단,502104001,제주 제주서부1,제주특별자치도 제주시 연동(서중입구 부근),4,4,0,1,3,0,33.493564,126.478483,"{type:Polygon,coordinates:[[[126.4807657,33.49...",2019-10-10
1755,2013114,2012,무단횡단,502104002,제주 제주서부2,제주특별자치도 제주시 연동(예나음악학원 부근),4,4,0,3,1,0,33.491605,126.489014,"{type:Polygon,coordinates:[[[126.4912967,33.49...",2019-10-10
1756,2013114,2012,무단횡단,502104003,제주 제주서부3,제주특별자치도 제주시 노형동(그랜드호텔사거 부근),5,5,0,3,2,0,33.485225,126.489959,"{type:Polygon,coordinates:[[[126.4922414,33.48...",2019-10-10
1757,2013114,2012,무단횡단,502104004,제주 제주서부4,제주특별자치도 제주시 노형동(떳다반점 부근),10,10,0,6,4,0,33.486812,126.480983,"{type:Polygon,coordinates:[[[126.4832655,33.48...",2019-10-10

In [48]:
# 20130602 사고지역관리번호가 20130602의 모든데이터

In [57]:
b[b['사고지역관리번호'] == 2013060].shape

(35, 16)

In [58]:
b[b['사고지역관리번호'] == 2013060].size

560

In [66]:
# 중상자수 >= 2

In [68]:
b[b['중상자수'] >= 2].shape

(7004, 16)

In [75]:
b[b['중상자수'] >= 2].iloc[0:3] # index상관없이

,사고지역관리번호,사고년도,사고유형구분,위치코드,시도시군구명,사고지역위치명,발생건수,사상자수,사망자수,중상자수,경상자수,부상자수,위도,경도,사고다발지역폴리곤정보,데이터기준일자
2,2013060,2012,스쿨존어린이,11290002,서울특별시 성북구2,서울특별시 성북구 동소문동7가(정덕초교 부근),2,2,0,2,0,0,37.597571,127.014564,"{type:Polygon,coordinates:[[[127.0169658,37.59...",2019-10-10
3,2013060,2012,스쿨존어린이,11290003,서울특별시 성북구3,서울특별시 성북구 석관동(석관초교 부근),3,3,0,2,1,0,37.610429,127.059596,"{type:Polygon,coordinates:[[[127.0619982,37.61...",2019-10-10
11,2013060,2012,스쿨존어린이,26350001,부산광역시 해운대구1,부산광역시 해운대구 반여동(장산초교 부근),2,2,0,2,0,0,35.199556,129.119107,"{type:Polygon,coordinates:[[[129.121437,35.201...",2019-10-10

In [76]:
b[b['중상자수'] >= 2].loc[2:3] # index로

,사고지역관리번호,사고년도,사고유형구분,위치코드,시도시군구명,사고지역위치명,발생건수,사상자수,사망자수,중상자수,경상자수,부상자수,위도,경도,사고다발지역폴리곤정보,데이터기준일자
2,2013060,2012,스쿨존어린이,11290002,서울특별시 성북구2,서울특별시 성북구 동소문동7가(정덕초교 부근),2,2,0,2,0,0,37.597571,127.014564,"{type:Polygon,coordinates:[[[127.0169658,37.59...",2019-10-10
3,2013060,2012,스쿨존어린이,11290003,서울특별시 성북구3,서울특별시 성북구 석관동(석관초교 부근),3,3,0,2,1,0,37.610429,127.059596,"{type:Polygon,coordinates:[[[127.0619982,37.61...",2019-10-10

In [77]:
# 중상자수 == 2 && 경상자수 > 1

In [81]:
b[(b['중상자수'] >= 2) & (b['경상자수'] > 2)]

,사고지역관리번호,사고년도,사고유형구분,위치코드,시도시군구명,사고지역위치명,발생건수,사상자수,사망자수,중상자수,경상자수,부상자수,위도,경도,사고다발지역폴리곤정보,데이터기준일자
42,2013097,2012,보행어린이,11290001,서울특별시 성북구1,서울특별시 성북구 종암동(종암동 근린생활시설 부근),4,5,0,2,3,0,37.599147,127.033915,"{type:Polygon,coordinates:[[[127.0355168,37.60...",2019-10-10
66,2013097,2012,보행어린이,11710005,서울특별시 송파구5,서울특별시 송파구 가락동(가락대림사거리 부근),4,6,0,2,4,0,37.498465,127.119842,"{type:Polygon,coordinates:[[[127.1214417,37.49...",2019-10-10
136,2013097,2012,보행어린이,41271003,경기도 안산시 상록구3,경기도 안산시 상록구 수암동(선경드림타운 부근),3,7,1,2,4,0,37.363344,126.876725,"{type:Polygon,coordinates:[[[126.8783213,37.36...",2019-10-10
165,2013097,2012,보행어린이,43111002,충청북도 청주시 상당구2,충청북도 청주시 상당구 탑동((굿모닝메디칼) 부근),4,6,0,3,3,0,36.631056,127.502186,"{type:Polygon,coordinates:[[[127.503767,36.632...",2019-10-10
179,2013097,2012,보행어린이,45113001,전라북도 전주시 덕진구1,전라북도 전주시 덕진구 인후동1가(대게나라 부근),5,5,0,2,3,0,35.826254,127.165245,"{type:Polygon,coordinates:[[[127.1668097,35.82...",2019-10-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10346,2019066,2018,무단횡단,220627001,대구 대구달서1,대구광역시 달서구 송현동(성당네거리 부근),7,7,1,3,3,0,35.837916,128.555698,"{type:Polygon,coordinates:[[[128.55839264,35.8...",2019-10-10
10357,2019066,2018,무단횡단,280341001,경기 고양1,경기도 고양시 덕양구 고양동(고양동우체국 부근),8,8,0,3,5,0,37.703854,126.902062,"{type:Polygon,coordinates:[[[126.90475708,37.7...",2019-10-10
10360,2019066,2018,무단횡단,280641002,경기 파주2,경기도 파주시 금촌동(우리은행 파주금융센터 부근),5,7,0,2,5,0,37.757022,126.773592,"{type:Polygon,coordinates:[[[126.77628656,37.7...",2019-10-10
10361,2019066,2018,무단횡단,280641003,경기 파주3,경기도 파주시 조리읍(봉일천우체국 부근),5,5,0,2,3,0,37.743755,126.806671,"{type:Polygon,coordinates:[[[126.80936607,37.7...",2019-10-10
10363,2019066,2018,무단횡단,280941001,경기 구리1,경기도 구리시 수택동(세븐일레븐 구리으뜸점 부근),6,6,0,2,4,0,37.598290,127.136542,"{type:Polygon,coordinates:[[[127.13923669,37.5...",2019-10-10